function Pistas(nombre,pista1,pista2,pista3,enlace){
    this.nombre= nombre,
    this.pista1=pista1,
    this.pista2=pista2,
    this.pista3=pista3,
    this.enlace=enlace
}
var palabra1=new Pistas('fotosíntesis',"Proceso que convierte energía lumínica en energía química.","Forma azucares a partir de agua y dióxido de carbono.","Libera oxígeno como subproducto.");
var palabra2=new Pistas('anatomía',"Ciencia que estudia la forma, topografía, ubicación, disposición y relación entre sí de los organos que componen la estructura de los seres vivos.","Es una de las llamadas Ciencias Básicas o Preclínicas de la medicina","La practican científicos denominados Anatomistas.");
var palabra3=new Pistas('aritmética','Su objetivo principal es estudiar los números y las operaciones elementales hechas con ellos.','Sus operaciones elementales son la adición, sustracción, multiplicación y división.','Se desarrolló de manera formal en la Antigua Grecia.');
var palabra4=new Pistas('biodiversidad','Comprende la variedad de ecosistemas y las diferencias genéticas dentro de cada especie.','Diversidad de especies tanto vegetales como animales que viven en un espacio determinado.','Diversidad biológica, conjunto de todos los seres vivos del planeta (animales, plantasy organizamos), el ambiente en el que viven (ecosistemas terrestres y marinos) y la relación que guardan con otras especies.','https://www.ecologistasenaccion.org/6296/biodiversidad-que-es-donde-se-encuentra-y-por-que-es-importante/');
var palabra5=new Pistas('heterótrofos','Seres vivos que no son capaces de autosustentarse a partir de la materia inorgánica del medio ambiente.','Necesitan consumir la materia orgánica de otros seres vivientes para poder nutrirse y continuar viviendo','Se clasifican según sus preferencias alimentarias en Herbívoros, Carnívoros, Detritófagos, Omnívoros.','https://concepto.de/heterotrofo/');
var palabra6=new Pistas('autótrofos','Seres vivos capaces de gestionar la producción de su propia energía, sacando provecho a los elementos ambientales','No necesita de otros seres vivos para nutrirse.','Sintetizan a partir de sustancias inorgánicas todo lo que necesitan para su metabolismo.','https://concepto.de/autotrofo/');
var palabra7=new Pistas('átomo','Es la unidad más básica de la materia con propiedades de un elemento químico. Aunque es una unidad básica, está compuesta de tres subestructuras.','El universo, las estrellas, galaxias, planetas y demás cuerpos celestes están hechos de esta unidad.','Se agrupan formando moléculas, y éstas constituyen todos los materiales que conocemos con las características físicas y químicas que observamos.','https://www.geoenciclopedia.com/que-es-el-atomo/');
var palabra8=new Pistas('astronomía','Ciencia que se ocupa del estudio de los cuerpos celestes del universo, incluidos planetas y sus satélites, cometas y meteoroides, estrellas, y materia interestelar, materia oscura, galaxias, etc.','Abarca el estudio de la formación y el desarrollo del Universo.','Se relaciona con la física mediante la astrofísica, la química mediante la astroquímica, y la biología con la astrobiología.','https://es.wikipedia.org/wiki/Astronom%C3%ADa');
var palabra9=new Pistas('física','Ciencia natural que estudia los componentes fundamentales del Universo, la energía, la materia, el espacio-tiempo y las interacciones fundamentales.','Ciencia básica estrechamente vinculada con las matemáticas y la lógica en la formulación y cuantificación de sus principios.','No es sólo una ciencia teórica; es también una ciencia experimental. Como toda ciencia, busca que sus conclusiones puedan ser verificables mediante experimentos y que la teoría pueda realizar predicciones de experimentos futuros basados en observaciones previas.','https://es.wikipedia.org/wiki/F%C3%ADsica');
var palabra10=new Pistas('biología','Ciencia que estudia los procesos naturales de los seres vivos, su anatomía, fisiología, evolución, desarrollo, distribución y relaciones.','Se ocupa de la descripción de las características y los comportamientos de los organismos individuales, como de las especies en su conjunto.','Estudia la estructura y la dinámica funcional comunes a todos los seres vivos, con el fin de establecer las leyes generales que rigen la vida orgánica y sus principios.','https://es.wikipedia.org/wiki/Biolog%C3%ADa');
var palabra11=new Pistas('química','Ciencia que estudia la composición, estructura y propiedades de la materia.','Tambien estudia los cambios que experimenta la materia durante las reacciones químicas y su relación con la energía.','Las disciplinas de esta ciencia se agrupan según la clase de materia bajo estudio o el tipo de estudio realizado.','https://es.wikipedia.org/wiki/Qu%C3%ADmica');
var palabra12=new Pistas('geología','Ciencia natural que estudia la composición y estructura tanto interna como superficial del planeta Tierra, y los procesos por los cuales ha ido evolucionando a lo largo del tiempo.','En la actualidad tiene una importancia fundamental en la exploración de yacimientos minerales, hidrocarburos, y evaluación de recursos hídricos subterráneos.','Tiene importancia fundamental en la prevención y entendimiento de fenómenos naturales (remoción de masas, terremotos, tsunamis, erupciones volcánicas, etc.).','https://es.wikipedia.org/wiki/Geolog%C3%ADa');
var palabra13=new Pistas();
var palabra14=new Pistas();
var palabra15=new Pistas();